SET(CMAKE_BUILD_TYPE "Release" CACHE STRING "")

SET(CMAKE_GENERATOR "Xcode" CACHE STRING "")

SET(CMAKE_CXX_FLAGS "-Wall -Wextra -isystem -O3 -DCGAL_NDEBUG" CACHE STRING "")

SET(CGAL_HEADER_ONLY ON CACHE BOOL "")

SET(WITH_GMP ON CACHE BOOL "")

SET(WITH_GMPXX OFF CACHE BOOL "")

SET(WITH_MPFR ON CACHE BOOL "")

SET(WITH_NTL OFF CACHE BOOL "")
